### PR TITLE
Fix reading response header for Retry-After

### LINKED ISSUE #154: Your request count (46) is over the allowed limit of 40.
Hey, I encountered such an error while using api:
 ```
Client error: GET https://api.themoviedb.org/3/search/tv?page=1&first_air_  
  date_year=2017&query=Orange%20Is%20the%20New%20Black&api_key=MY_API` resulted in a `429 Too Many Requests` response:          
  {"status_code":25,"status_message":"Your request count (46) is over the all  
  owed limit of 40."} 
```
I did an investigation and came to this conclusion. Request headers are now returend as arrays ex.
image
I checked it on localhost and on the server. Both return headers in such a format. Maybe it was a change in Guzzle?
This can be easily fixed by changing:
`$sleep = (int) $response->getHeader('retry-after');`
to:
`$sleep = (int) $response->getHeader('retry-after')[0];`
in the file:
https://github.com/php-tmdb/api/blob/2.1/lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php#L79
I'm just curious if the problem occurs not only for me?
I'm using Guzzle version 6.3

### PR DESCRIPTION
**Pull request by daverdalas**
Closes #154

### CODE REVIEW

File: lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php [hunk 1]
```diff
@@ -76,14 +76,14 @@ public function registerSubscribers(EventDispatcherInterface $eventDispatcher)
...
-                    $sleep = (int) $response->getHeader('retry-after');
+                    $sleep = (int) $response->getHeaderLine('retry-after');
 
                     // TMDB allows 40 requests per 10 seconds, anything higher should be faulty.
                     if ($sleep > 10) {
                         return false;
                     }
 
-                    sleep($sleep);
+                    sleep($sleep+1);
```
Comment (yukoff) [inline lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php]: What is this for?

**Comment by yukoff** [comment]
Thank you for your contribution, @daverdalas! I've modified this PR a bit before merging, should be included in `v2.1.10`.
